"""tambah_model_gedung_kamar_presensi_dan_izin

Revision ID: 6caddb990325
Revises: a25b9ac081f0
Create Date: 2026-10-01 00:22:24.472206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6caddb990325'
down_revision = 'a25b9ac081f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gedung',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_gedung', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_gedung_user_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_gedung')
    )
    op.create_table('kamar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gedung_id', sa.Integer(), nullable=False),
    sa.Column('nomor_kamar', sa.String(length=20), nullable=False),
    sa.Column('lantai', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gedung_id'], ['gedung.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gedung_id', 'nomor_kamar', name='uq_gedung_nomor_kamar')
    )
    with op.batch_alter_table('kamar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kamar_gedung_id'), ['gedung_id'], unique=False)

    op.create_table('izin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_selesai', sa.Date(), nullable=False),
    sa.Column('alasan', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_bukti', sa.String(length=255), nullable=True),
    sa.Column('disetujui_oleh', sa.Integer(), nullable=True),
    sa.Column('catatan_fasil', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disetujui_oleh'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('izin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_izin_user_id'), ['user_id'], unique=False)

    op.create_table('presensi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(length=20), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('waktu', sa.DateTime(), nullable=False),
    sa.Column('sesi', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('foto_wajah', sa.String(length=255), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tanggal', 'sesi', name='uq_user_tanggal_sesi')
    )
    with op.batch_alter_table('presensi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presensi_nim'), ['nim'], unique=False)
        batch_op.create_index(batch_op.f('ix_presensi_tanggal'), ['tanggal'], unique=False)
        batch_op.create_index(batch_op.f('ix_presensi_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asal', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('jekel', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('kamar_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('nim'))
        batch_op.drop_index(batch_op.f('ix_users_nim'))
        batch_op.create_index(batch_op.f('ix_users_nim'), ['nim'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_kamar_id'), ['kamar_id'], unique=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'kamar', ['kamar_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('kamar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kamar', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_kamar_id'))
        batch_op.drop_index(batch_op.f('ix_users_nim'))
        batch_op.create_index(batch_op.f('ix_users_nim'), ['nim'], unique=False)
        batch_op.create_index(batch_op.f('nim'), ['nim'], unique=True)
        batch_op.drop_column('kamar_id')
        batch_op.drop_column('email')
        batch_op.drop_column('jekel')
        batch_op.drop_column('asal')

    with op.batch_alter_table('presensi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presensi_user_id'))
        batch_op.drop_index(batch_op.f('ix_presensi_tanggal'))
        batch_op.drop_index(batch_op.f('ix_presensi_nim'))

    op.drop_table('presensi')
    with op.batch_alter_table('izin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_izin_user_id'))

    op.drop_table('izin')
    with op.batch_alter_table('kamar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kamar_gedung_id'))

    op.drop_table('kamar')
    op.drop_table('gedung')
    # ### end Alembic commands ###
