"""add_gedung_id_to_area_and_presensi

Revision ID: 726c8205a1c2
Revises: 9fb4f9c5c26f
Create Date: 2026-10-06 00:08:24.179084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726c8205a1c2'
down_revision = '9fb4f9c5c26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('area_absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gedung_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_area_absensi_gedung_id'), ['gedung_id'], unique=False)
        batch_op.create_foreign_key(None, 'gedung', ['gedung_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('presensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gedung_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_presensi_gedung_id'), ['gedung_id'], unique=False)
        batch_op.create_foreign_key(None, 'gedung', ['gedung_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presensi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_presensi_gedung_id'))
        batch_op.drop_column('gedung_id')

    with op.batch_alter_table('area_absensi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_area_absensi_gedung_id'))
        batch_op.drop_column('gedung_id')

    # ### end Alembic commands ###
