"""tambah_area_absensi_dan_akurasi_presensi

Revision ID: 9fb4f9c5c26f
Revises: 6caddb990325
Create Date: 2026-10-05 21:56:06.792528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb4f9c5c26f'
down_revision = '6caddb990325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_absensi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('polygon_wkt', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dibuat_oleh', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sesi_absensi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_sesi', sa.String(length=100), nullable=False),
    sa.Column('tipe_sesi', sa.String(length=20), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('waktu_mulai', sa.DateTime(), nullable=False),
    sa.Column('waktu_selesai', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dibuat_oleh', sa.Integer(), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sesi_absensi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesi_absensi_dibuat_oleh'), ['dibuat_oleh'], unique=False)
        batch_op.create_index(batch_op.f('ix_sesi_absensi_tanggal'), ['tanggal'], unique=False)

    with op.batch_alter_table('gedung', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_gedung_user_id', 'users', ['user_id'], ['id'], ondelete='SET NULL', use_alter=True)

    with op.batch_alter_table('presensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accuracy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('area_absensi_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'area_absensi', ['area_absensi_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presensi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('area_absensi_id')
        batch_op.drop_column('accuracy')

    with op.batch_alter_table('gedung', schema=None) as batch_op:
        batch_op.drop_constraint('fk_gedung_user_id', type_='foreignkey')

    with op.batch_alter_table('sesi_absensi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesi_absensi_tanggal'))
        batch_op.drop_index(batch_op.f('ix_sesi_absensi_dibuat_oleh'))

    op.drop_table('sesi_absensi')
    op.drop_table('area_absensi')
    # ### end Alembic commands ###
