"""make_waktu_selesai_nullable_in_sesi_absensi

Revision ID: b8f9e21a4c5d
Revises: 726c8205a1c2
Create Date: 2026-10-07 17:21:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f9e21a4c5d'
down_revision = '726c8205a1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sesi_absensi', schema=None) as batch_op:
        batch_op.alter_column('waktu_selesai',
                              existing_type=sa.DateTime(),
                              nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sesi_absensi', schema=None) as batch_op:
        batch_op.alter_column('waktu_selesai',
                              existing_type=sa.DateTime(),
                              nullable=False)
    # ### end Alembic commands ###
